Inteligentne podlewanie/InteligentnePodlewanie/InteligentnePodlewanieMvc/Controllers/ApplianceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InteligentnePodlewanieMvc.Models;
using WebMatrix.WebData;
using InteligentnePodlewanieMvc.Filters;

namespace InteligentnePodlewanieMvc.Controllers
{
    public class ApplianceController : Controller
    {
        //
        // GET: /Appliance/

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult List()
        {
            var db = new ZadaniaContextDb();
            if (WebSecurity.IsCurrentUser("admin"))
            {
                return View(db.UrzadzenieSet.ToList());
            }
            else
            {
                var Query1 = from query1 in db.UrzadzenieSet.ToList()
                             where query1.UzytkownikId == WebSecurity.GetUserId(User.Identity.Name)
                             select query1;

                return View(Query1.ToList());
            }
        }

        //
        // GET: /Appliance/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Appliance/Create
        [Authorize(Roles = "AdminUser")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Appliance/Create
        [Authorize(Roles = "AdminUser")]
        [HttpPost]
        [InitializeSimpleMembership]
        public ActionResult Create(Urzadzenie appliance)
        {
            try
            {
                var db = new ZadaniaContextDb();
                appliance.Wersja = 1;
                db.UrzadzenieSet.Add(appliance);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Appliance/Edit/5
        [Authorize(Roles = "AdminUser")]
        //[InitializeSimpleMembership]
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Appliance/Edit/5

        [HttpPost]
        [Authorize(Roles = "AdminUser")]
        [InitializeSimpleMembership]
        public ActionResult Edit(int id, Urzadzenie model)
        {
            try
            {
                var db = new ZadaniaContextDb();

                Urzadzenie appliance = db.UrzadzenieSet.First(i => i.Id == id);
                appliance.Nazwa = model.Nazwa;
                appliance.Kod = model.Kod;
                appliance.Wersja++;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Appliance/Delete/5
        [Authorize(Roles = "AdminUser")]
        [InitializeSimpleMembership]
        public ActionResult Delete(int id)
        {
            var db = new ZadaniaContextDb();
            Urzadzenie appliance = db.UrzadzenieSet.First(i => i.Id == id);
            return View(appliance);
        }

        //
        // POST: /Appliance/Delete/5

        [HttpPost]
        [Authorize(Roles = "AdminUser")]
        [InitializeSimpleMembership]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var db = new ZadaniaContextDb();
                Urzadzenie appliance = db.UrzadzenieSet.First(i => i.Id == id);
                db.UrzadzenieSet.Remove(appliance);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
    }
}

Inteligentne podlewanie/InteligentnePodlewanie/InteligentnePodlewanieMvc/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InteligentnePodlewanieMvc.Models;
using InteligentnePodlewanieMvc.Filters;
using WebMatrix.WebData;

namespace InteligentnePodlewanieMvc.Controllers
{
    public class TaskController : Controller
    {
        //
        // GET: /Task/

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult List(int ApplianceId)
        {
            ViewData["ApplianceId"] = ApplianceId;
            var db = new ZadaniaContextDb();

            var Query1 = from query1 in db.UrzadzenieSet.ToList()
                         where query1.UzytkownikId == WebSecurity.GetUserId(User.Identity.Name)
                         select query1;

            bool is_authenticated = false;
            foreach (Urzadzenie row in Query1.ToList())
            {
                if (row.Id == ApplianceId)
                {
                    ViewBag.ApplianceName = row.Nazwa;
                    is_authenticated = true;
                    break;
                }
            }

            if (is_authenticated)
            {
                var Query3 = from query3 in db.ZadanieSet.ToList()
                             where query3.UrzadzenieId == ApplianceId
                             select query3;

                return View(Query3.ToList());
            }
            else
            {
                return View("List");
            }
        }

        //
        // GET: /Task/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Task/Create

        public ActionResult Create(int ApplianceId)
        {
            return View();
        }

        //
        // POST: /Task/Create

        [HttpPost]
        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult Create(Zadanie task, int ApplianceId, string chosenDate, string chosenHour)
        {
            try
            {
                var db = new ZadaniaContextDb();

                var Query1 = from query1 in db.UrzadzenieSet.ToList()
                             where query1.UzytkownikId == WebSecurity.GetUserId(User.Identity.Name)
                             select query1;

                bool is_authenticated = false;
                foreach (Urzadzenie row in Query1.ToList())
                {
                    if (row.Id == ApplianceId)
                    {
                        is_authenticated = true;
                        break;
                    }
                }

                if (is_authenticated)
                {
                    chosenDate += " " + chosenHour;
                    task.DataCzas = DateTime.Parse(chosenDate);
                    task.UrzadzenieId = ApplianceId;
                    db.ZadanieSet.Add(task);
                    db.SaveChanges();                    
                }
                return RedirectToAction("List", new { ApplianceId = ApplianceId });
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Task/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Task/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Task/Delete/5
        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult Delete(int id)
        {
            var db = new ZadaniaContextDb();
            Zadanie task = db.ZadanieSet.First(i => i.Id == id);
            return View(task);            
        }

        //
        // POST: /Task/Delete/5

        [HttpPost]
        [Authorize]
        [InitializeSimpleMembership]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var db = new ZadaniaContextDb();
                Zadanie task = db.ZadanieSet.First(i => i.Id == id);
                db.ZadanieSet.Remove(task);
                db.SaveChanges();
                return RedirectToAction("List", new { ApplianceId = task.UrzadzenieId });
            }
            catch
            {
                return View();
            }
        }
    }
}

Inteligentne podlewanie/InteligentnePodlewanie/InteligentnePodlewanieMvc/Views/Appliance/Create.cshtml
@model InteligentnePodlewanieMvc.Models.Urzadzenie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Urzadzenie</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UzytkownikId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UzytkownikId)
            @Html.ValidationMessageFor(model => model.UzytkownikId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nazwa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nazwa)
            @Html.ValidationMessageFor(model => model.Nazwa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Kod)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Kod)
            @Html.ValidationMessageFor(model => model.Kod)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inteligentne podlewanie/InteligentnePodlewanie/InteligentnePodlewanieMvc/Views/Appliance/Delete.cshtml
@model InteligentnePodlewanieMvc.Models.Urzadzenie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Urzadzenie</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nazwa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nazwa)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Kod)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Kod)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Wersja)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Wersja)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "List")
    </p>
}

Inteligentne podlewanie/InteligentnePodlewanie/InteligentnePodlewanieMvc/Views/Appliance/Edit.cshtml
@model InteligentnePodlewanieMvc.Models.Urzadzenie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Urzadzenie</legend>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UzytkownikId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nazwa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nazwa)
            @Html.ValidationMessageFor(model => model.Nazwa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Kod)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Kod)
            @Html.ValidationMessageFor(model => model.Kod)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inteligentne podlewanie/InteligentnePodlewanie/InteligentnePodlewanieMvc/Views/Appliance/List.cshtml
@model IEnumerable<InteligentnePodlewanieMvc.Models.Urzadzenie>

@{
    ViewBag.Title = "Moje Urządzenia";
    bool isAdmin = false;
    if (WebSecurity.GetUserId(User.Identity.Name) == 4)
    {
        isAdmin = true;
    }
}

<h2>Moje urządzenia</h2>

@{if (isAdmin)
  {
    <text>
    <p>
        @Html.ActionLink("Utwórz nowe urządzenie", "Create")
    </p>
    </text>
  }
}
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wersja)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Nazwa, "List", "Task", new { ApplianceId = item.Id }, new { ApplianceId = item.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wersja)
            </td>
            @{
                if (isAdmin)
                {
                    <text>
                    <td>
                        @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }) |            
                        @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
                    </td>
                    </text>
                }
            }
        </tr>
    }

</table>